// SPDX-License-Identifier: MIT
// Reuse the level-3 dispatch implementation after mapping its public and
// namespaced symbols to the level-5 256s parameter set.

#include <oqs/oqs.h>

#undef OQS_SIG_alg_aimer_v3_192f
#undef OQS_SIG_aimer_v3_192f_length_public_key
#undef OQS_SIG_aimer_v3_192f_length_secret_key
#undef OQS_SIG_aimer_v3_192f_length_signature

#define AIMER_V3_CLAIMED_NIST_LEVEL 5
#define OQS_SIG_alg_aimer_v3_192f OQS_SIG_alg_aimer_v3_256s
#define OQS_SIG_aimer_v3_192f_length_public_key OQS_SIG_aimer_v3_256s_length_public_key
#define OQS_SIG_aimer_v3_192f_length_secret_key OQS_SIG_aimer_v3_256s_length_secret_key
#define OQS_SIG_aimer_v3_192f_length_signature OQS_SIG_aimer_v3_256s_length_signature
#define OQS_SIG_aimer_v3_192f_new OQS_SIG_aimer_v3_256s_new
#define OQS_SIG_aimer_v3_192f_keypair OQS_SIG_aimer_v3_256s_keypair
#define OQS_SIG_aimer_v3_192f_sign OQS_SIG_aimer_v3_256s_sign
#define OQS_SIG_aimer_v3_192f_sign_with_ctx_str OQS_SIG_aimer_v3_256s_sign_with_ctx_str
#define OQS_SIG_aimer_v3_192f_verify OQS_SIG_aimer_v3_256s_verify
#define OQS_SIG_aimer_v3_192f_verify_with_ctx_str OQS_SIG_aimer_v3_256s_verify_with_ctx_str
#define samsungsds_aimer_192f_ref_crypto_sign_keypair samsungsds_aimer_256s_ref_crypto_sign_keypair
#define samsungsds_aimer_192f_ref_crypto_sign_signature samsungsds_aimer_256s_ref_crypto_sign_signature
#define samsungsds_aimer_192f_ref_crypto_sign_verify samsungsds_aimer_256s_ref_crypto_sign_verify
#define samsungsds_aimer_192f_avx2_crypto_sign_keypair samsungsds_aimer_256s_avx2_crypto_sign_keypair
#define samsungsds_aimer_192f_avx2_crypto_sign_signature samsungsds_aimer_256s_avx2_crypto_sign_signature
#define samsungsds_aimer_192f_avx2_crypto_sign_verify samsungsds_aimer_256s_avx2_crypto_sign_verify
#define samsungsds_aimer_192f_opt_crypto_sign_keypair samsungsds_aimer_256s_opt_crypto_sign_keypair
#define samsungsds_aimer_192f_opt_crypto_sign_signature samsungsds_aimer_256s_opt_crypto_sign_signature
#define samsungsds_aimer_192f_opt_crypto_sign_verify samsungsds_aimer_256s_opt_crypto_sign_verify

#include "sig_aimer_v3_192f_dispatch.c"
