// SPDX-License-Identifier: MIT
#ifndef AIMER_V3_OQS_KAT_COMPAT_256S_H
#define AIMER_V3_OQS_KAT_COMPAT_256S_H

#include <oqs/oqs.h>

#undef OQS_SIG_alg_aimer_v3_192f
#undef OQS_SIG_aimer_v3_192f_length_public_key
#undef OQS_SIG_aimer_v3_192f_length_secret_key
#undef OQS_SIG_aimer_v3_192f_length_signature
#define OQS_SIG_alg_aimer_v3_192f OQS_SIG_alg_aimer_v3_256s
#define OQS_SIG_aimer_v3_192f_length_public_key OQS_SIG_aimer_v3_256s_length_public_key
#define OQS_SIG_aimer_v3_192f_length_secret_key OQS_SIG_aimer_v3_256s_length_secret_key
#define OQS_SIG_aimer_v3_192f_length_signature OQS_SIG_aimer_v3_256s_length_signature
#define CRYPTO_ALGNAME "aimer-256s"
#include "kat_compat_192f.h"

#endif // AIMER_V3_OQS_KAT_COMPAT_256S_H
